# Configuração para a Netlify tratar o projeto como uma Single-Page Application.

[build]
  # O diretório que contém o site final a ser publicado.
  # Como não há um passo de compilação (build), é o diretório raiz.
  publish = "/"

[[redirects]]
  # Esta regra redireciona todas as requisições para o index.html,
  # permitindo que o React Router controle a navegação no lado do cliente.
  from = "/*"
  to = "/index.html"
  status = 200
